#!/usr/bin/env python3
"""
Export Patreon cookies from Chrome to Netscape format for gallery-dl.

This script extracts all Patreon cookies from your Chrome browser
and saves them in Netscape format that gallery-dl can use.

Usage:
    python export_patreon_cookies.py

Output:
    patreon_cookies.txt - Cookie file in Netscape format
"""

import sqlite3
import os
import shutil
from pathlib import Path
from datetime import datetime


def find_chrome_cookies_db():
    """Find Chrome's cookies database file with Patreon cookies."""
    # macOS path
    chrome_cookies = Path.home() / "Library/Application Support/Google/Chrome"
    
    # Try different profiles
    profiles = [
        ("Default", chrome_cookies / "Default/Cookies"),
        ("Profile 1", chrome_cookies / "Profile 1/Cookies"),
        ("Profile 2", chrome_cookies / "Profile 2/Cookies"),
        ("Profile 3", chrome_cookies / "Profile 3/Cookies"),
        ("Profile 4", chrome_cookies / "Profile 4/Cookies"),
    ]
    
    print("[INFO] Searching for Chrome profile with Patreon cookies...")
    
    for profile_name, profile_path in profiles:
        if not profile_path.exists():
            continue
        
        # Check if this profile has Patreon cookies
        try:
            # Copy to temp first to avoid lock issues
            temp_db = "/tmp/chrome_cookies_check.db"
            shutil.copy2(profile_path, temp_db)
            
            conn = sqlite3.connect(temp_db)
            cursor = conn.cursor()
            
            cursor.execute("""
                SELECT COUNT(*) 
                FROM cookies 
                WHERE host_key LIKE '%patreon.com%'
            """)
            
            count = cursor.fetchone()[0]
            conn.close()
            os.remove(temp_db)
            
            if count > 0:
                print(f"[INFO] Found Patreon cookies in Chrome {profile_name} ({count} cookies)")
                return profile_path
            else:
                print(f"[INFO] Chrome {profile_name} has no Patreon cookies, skipping")
        
        except Exception as e:
            print(f"[WARNING] Error checking {profile_name}: {e}")
            if os.path.exists(temp_db):
                os.remove(temp_db)
            continue
    
    return None


def export_patreon_cookies(output_file="patreon_cookies.txt"):
    """
    Export Patreon cookies from Chrome to Netscape format.
    
    Args:
        output_file: Output file path
    
    Returns:
        True if successful, False otherwise
    """
    cookies_db = find_chrome_cookies_db()
    
    if not cookies_db:
        print("[ERROR] Chrome cookies database not found!")
        print("[INFO] Make sure Chrome is installed and you've visited Patreon")
        return False
    
    # Copy database to temp location (Chrome locks the original)
    temp_db = "/tmp/chrome_cookies_copy.db"
    try:
        shutil.copy2(cookies_db, temp_db)
    except Exception as e:
        print(f"[ERROR] Failed to copy cookies database: {e}")
        print("[INFO] Make sure Chrome is closed, or try again")
        return False
    
    try:
        # Connect to copied database
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()
        
        # Query Patreon cookies
        cursor.execute("""
            SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key LIKE '%patreon.com%'
            ORDER BY host_key, name
        """)
        
        cookies = cursor.fetchall()
        conn.close()
        
        if not cookies:
            print("[ERROR] No Patreon cookies found!")
            print("[INFO] Make sure you're logged into Patreon in Chrome")
            return False
        
        print(f"[INFO] Found {len(cookies)} Patreon cookies")
        
        # Write to Netscape format
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export_patreon_cookies.py\n")
            f.write("# Edit at your own risk.\n\n")
            
            for cookie in cookies:
                host_key, name, value, path, expires_utc, is_secure, is_httponly = cookie
                
                # Convert Chrome's expires_utc to Unix timestamp
                # Chrome uses microseconds since 1601-01-01
                # Unix uses seconds since 1970-01-01
                if expires_utc:
                    # Chrome epoch: 1601-01-01
                    # Unix epoch: 1970-01-01
                    # Difference: 11644473600 seconds
                    unix_timestamp = (expires_utc / 1000000) - 11644473600
                    expires = int(unix_timestamp)
                else:
                    expires = 0
                
                # Netscape format:
                # domain flag path secure expiration name value
                domain = host_key
                flag = "TRUE" if domain.startswith('.') else "FALSE"
                path = path or "/"
                secure = "TRUE" if is_secure else "FALSE"
                
                line = f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                f.write(line)
        
        print(f"[SUCCESS] Cookies exported to: {output_file}")
        print(f"[INFO] Cookie details:")
        
        # Show important cookies
        important = ['session_id', '__cf_bm', 'cf_clearance']
        for cookie in cookies:
            name = cookie[1]
            if name in important or 'cf' in name.lower():
                print(f"  - {name}: {cookie[2][:20]}...")
        
        return True
        
    except Exception as e:
        print(f"[ERROR] Failed to export cookies: {e}")
        return False
    
    finally:
        # Clean up temp file
        if os.path.exists(temp_db):
            os.remove(temp_db)


if __name__ == "__main__":
    print("=" * 60)
    print("Patreon Cookie Exporter")
    print("=" * 60)
    print()
    
    success = export_patreon_cookies()
    
    if success:
        print()
        print("[NEXT STEPS]")
        print("1. Upload the cookie file to your server:")
        print("   scp patreon_cookies.txt deploy@YOUR_SERVER_IP:~/patreon_cookies.txt")
        print()
        print("2. Test with gallery-dl:")
        print("   gallery-dl --cookies ~/patreon_cookies.txt https://www.patreon.com/vama/posts")
        print()
        print("[WARNING] These cookies expire! You may need to re-export periodically.")
    else:
        print()
        print("[TROUBLESHOOTING]")
        print("- Make sure Chrome is installed")
        print("- Make sure you're logged into Patreon in Chrome")
        print("- Try closing Chrome and running this script again")
        print("- Check if you're using a different Chrome profile")
