#!/usr/bin/env python3
"""
Export Patreon cookies from Chrome to Netscape format for gallery-dl.

This script extracts all Patreon cookies from your Chrome browser
and saves them in Netscape format that gallery-dl can use.

Requirements:
    pip install pycookiecheat

Usage:
    python export_patreon_cookies.py

Output:
    patreon_cookies.txt - Cookie file in Netscape format
"""

import os
import shutil
import sqlite3
from pathlib import Path
from datetime import datetime

try:
    from pycookiecheat import chrome_cookies
except ImportError:
    print("[ERROR] pycookiecheat not installed!")
    print("[INFO] Install with: pip install pycookiecheat")
    print("[INFO] Or: python3 -m pip install pycookiecheat")
    exit(1)


def find_chrome_profile_with_patreon():
    """Find which Chrome profile has Patreon cookies."""
    # macOS path
    chrome_base = Path.home() / "Library/Application Support/Google/Chrome"
    
    # Try different profiles
    profiles = [
        "Default",
        "Profile 1",
        "Profile 2",
        "Profile 3",
        "Profile 4",
    ]
    
    print("[INFO] Searching for Chrome profile with Patreon cookies...")
    
    for profile_name in profiles:
        profile_path = chrome_base / profile_name / "Cookies"
        
        if not profile_path.exists():
            continue
        
        # Check if this profile has Patreon cookies
        try:
            # Copy to temp first to avoid lock issues
            temp_db = "/tmp/chrome_cookies_check.db"
            shutil.copy2(profile_path, temp_db)
            
            conn = sqlite3.connect(temp_db)
            cursor = conn.cursor()
            
            cursor.execute("""
                SELECT COUNT(*) 
                FROM cookies 
                WHERE host_key LIKE '%patreon.com%'
            """)
            
            count = cursor.fetchone()[0]
            conn.close()
            os.remove(temp_db)
            
            if count > 0:
                print(f"[INFO] Found Patreon cookies in Chrome {profile_name} ({count} cookies)")
                return profile_name
            else:
                print(f"[INFO] Chrome {profile_name} has no Patreon cookies, skipping")
        
        except Exception as e:
            print(f"[WARNING] Error checking {profile_name}: {e}")
            if os.path.exists(temp_db):
                os.remove(temp_db)
            continue
    
    return None


def export_patreon_cookies(output_file="patreon_cookies.txt"):
    """
    Export Patreon cookies from Chrome to Netscape format using pycookiecheat.
    
    Args:
        output_file: Output file path
    
    Returns:
        True if successful, False otherwise
    """
    # First, find which profile has Patreon cookies
    profile_name = find_chrome_profile_with_patreon()
    
    if not profile_name:
        print("[ERROR] No Chrome profile with Patreon cookies found!")
        print("[INFO] Make sure you're logged into Patreon in Chrome")
        return False
    
    print(f"[INFO] Using Chrome {profile_name}")
    print("[INFO] Extracting and decrypting cookies...")
    
    try:
        # Use pycookiecheat to get decrypted cookies for patreon.com
        # This handles Chrome's encryption automatically
        # Pass the profile name to use the correct profile
        cookies_dict = chrome_cookies(
            'https://www.patreon.com',
            browser='chrome',
            cookie_file=str(Path.home() / "Library/Application Support/Google/Chrome" / profile_name / "Cookies")
        )
        
        if not cookies_dict:
            print("[ERROR] No Patreon cookies found!")
            print("[INFO] Make sure you're logged into Patreon in Chrome")
            return False
        
        print(f"[INFO] Found {len(cookies_dict)} Patreon cookies")
        
        # Write to Netscape format
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export_patreon_cookies.py\n")
            f.write("# Edit at your own risk.\n\n")
            
            for name, value in cookies_dict.items():
                # pycookiecheat returns simple name:value dict
                # We need to construct full Netscape format
                # Use sensible defaults for Patreon cookies
                
                domain = ".patreon.com"
                flag = "TRUE"
                path = "/"
                secure = "TRUE"
                expires = "0"  # Session cookie
                
                line = f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                f.write(line)
        
        print(f"[SUCCESS] Cookies exported to: {output_file}")
        print(f"[INFO] Cookie details:")
        
        # Show important cookies
        important = ['session_id', '__cf_bm', 'cf_clearance']
        for name, value in cookies_dict.items():
            if name in important or 'cf' in name.lower():
                print(f"  - {name}: {value[:20]}..." if len(value) > 20 else f"  - {name}: {value}")
        
        return True
        
    except Exception as e:
        print(f"[ERROR] Failed to export cookies: {e}")
        print(f"[INFO] Error details: {type(e).__name__}: {str(e)}")
        return False


if __name__ == "__main__":
    print("=" * 60)
    print("Patreon Cookie Exporter")
    print("=" * 60)
    print()
    
    success = export_patreon_cookies()
    
    if success:
        print()
        print("[NEXT STEPS]")
        print("1. Upload the cookie file to your server:")
        print("   scp patreon_cookies.txt deploy@YOUR_SERVER_IP:~/patreon_cookies.txt")
        print()
        print("2. Test with gallery-dl:")
        print("   gallery-dl --cookies ~/patreon_cookies.txt https://www.patreon.com/vama/posts")
        print()
        print("[WARNING] These cookies expire! You may need to re-export periodically.")
    else:
        print()
        print("[TROUBLESHOOTING]")
        print("- Make sure Chrome is installed")
        print("- Make sure you're logged into Patreon in Chrome")
        print("- Try closing Chrome and running this script again")
        print("- Check if you're using a different Chrome profile")
